### ISSUE TITLE
没有适配iPhoneX系列的底部区域

### ISSUE THREAD

**Issue by Smiacter** [mcuking/mobile-web-best-practice#11]
iPhoneX系列底部会多出一块，如何较好的适配底部安全区域？包括含有TabBar和没有TabBar界面的颜色融合等。不只是iPhoneX系列，iPhone相关的底部都会多出，应该是状态栏的高度。

![image](https://user-images.githubusercontent.com/5238096/105954945-73e79700-60b0-11eb-9da4-e3c26e009611.png)

**Comment by mcuking** [comment]
很抱歉这么久才回复你，目前兼容 iPhoneX 等机型底部留白问题主要操作如下：

1. 首先，给 html 的 viewport meta 标签添加一个扩展viewport-fit，用于设置网页在手机的可视窗口的布局方式，要适配 iPhoneX 必须设置 `viewport-fit=cover`，即：

```html
<meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,viewport-fit=cover"/>
```

2. 然后通过 env() 和 constant() 设置安全区域与边界的距离

    env() 和 constant() 函数有四个值：
    - safe-area-inset-left：安全区域距离左边边界距离
    - safe-area-inset-right：安全区域距离右边边界距离
    - safe-area-inset-top：安全区域距离顶部边界距离
    - safe-area-inset-bottom：安全区域距离底部边界距离
   
    底部兼容只需设置bottom边距即可

    ```css
    padding-bottom: constant(safe-area-inset-bottom); /* 兼容 iOS < 11.2 */ 
    padding-bottom: env(safe-area-inset-bottom); /* 兼容 iOS >= 11.2 */
    ```

    已经将用于兼容的代码推到远程仓库了，可点击查看。
