### ISSUE TITLE
npm run build编译 异常 

### ISSUE THREAD

**Issue by paulloo** [mcuking/mobile-web-best-practice#12]
` ERROR  Failed to compile with 1 error                                                                           下午2:41:23
 error  in ./src/utils/swipe-right-mixin.ts

Syntax Error: Bad character escape sequence. (2:92)
  1 | /* @babel/template */;
> 2 | window.$sentry.log({error: e, fileName: '\github\mobile-web-best-practice\src\utils\swipe-right-mixin.ts', lineNo: undefined, scope: '_isNativeReflectConstruct()'})
    |                                                                                            ^
    =============

 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--13-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/quote/index.vue?vue&type=script&lang=ts& 26:0-56 126:9-24
 @ ./src/views/quote/index.vue?vue&type=script&lang=ts&
 @ ./src/views/quote/index.vue
 @ ./src/router/router-list.ts
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mobile-web-best-practice@1.2.8 build: `vue-cli-service build && rm -rf dist/js/*.js.map`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mobile-web-best-practice@1.2.8 build script.`

**Comment by mcuking** [comment]
@paulloo 你好，能否提供下系统信息和 node 版本？我在 mac 系统和 linux 系统都是测试了下，貌似没这个问题

**Comment by biology-w** [comment]
![image](https://user-images.githubusercontent.com/25600705/147334781-6a84a266-cdc6-4c9e-8cfa-52c68b711fc7.png)
windows7
node 12.22.0
在执行npm run build 的时候，路径里面含有 \u 转义失败了。
我把swipe-right-mixin.ts文件放在新建文件mixin下就好了

**Comment by mcuking** [comment]
了解了
