### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by onlyhy** [mcuking/mobile-web-best-practice#13]
volumes中的挂载项目
目前是 `./:/usr/share/nginx/html/`
应该是`./dist:/usr/share/nginx/html/`吧？

**Comment by mcuking** [comment]
[fix: 将 docker 挂载dist目录向上提升一级，以解决删除并重新生成dist后导致文件访问权限问题](https://github.com/mcuking/mobile-web-best-practice/commit/d8e46373f6f92815d41e08c383d454a2740fc0f5)

当时为了解决这个问题，所以才修改了 docker-compose.yml，同时也修改了 nginx.conf 相关配置

我更新一下 README，说明一下这个问题
