### ISSUE TITLE
Mask 页面 频繁点击触发onTap事件导致<li></li>元素放大

### ISSUE THREAD

**Issue by zhourusheng** [mcuking/mobile-web-best-practice#4]
![微信截图_20190925145056](https://user-images.githubusercontent.com/33885944/65576235-25018d00-dfa4-11e9-8ba9-4d97f94f40d4.png)

**Comment by mcuking** [comment]
首先很感谢提出问题，下午调试看了下，大致原因已经找到：

当点击卡片触发 onTap 事件后，调用 TweenMax.to 方法对当前点击的元素 e.target 进行放大，即向 e.target.style 动态添加  transform: scale(1.1, 1.1)。但当卡片正在放大的过程中，点击获取的元素的大小已经比原来大了，所以再动态添加 transform: scale(1.1, 1.1) 时，就会导致动画完成时无法回到原始大小了。

你可能也会发现一个问题，点击频率不同，最终卡片恢复的大小也是不同的，大致就是这个原理导致的。

目前我这边通过比较 trick 的方式解决的： 调用 onTap 方法时，我会对 e.target.style.transform 进行校验，查看是否是 ‘’ （第一次点击）或者 ‘matrix(1, 0, 0, 1, 0, 0)’ （动画完成后），如果是，才会调用 
TweenMax.to 方法。

如果有更好的方式，欢迎提出来一起交流。
