### ISSUE TITLE
"out-of-memory crash"报错,会直接把浏览器卡死

### ISSUE THREAD

**Issue by chungchaos** [mcuking/mobile-web-best-practice#5]
新建任务页面

**Comment by mcuking** [comment]
首先很感谢帮忙提出问题。

问题已经定位了，主要是因为 vant 的时间选择组件的 min-data 参数的设置导致的。具体原因如下图：
![image](https://user-images.githubusercontent.com/22924912/69844831-d5dc1f00-12a8-11ea-95fb-3dabff6bbe9f.png)

问题已修复～
