### ISSUE TITLE
文章描述错误

### ISSUE THREAD

**Issue by Wermdany** [mcuking/mobile-web-best-practice#9]
您好，文章和项目对我受益很大，但是有一点描述错误

在
https://github.com/mcuking/mobile-web-best-practice#scrollbehavior

![image](https://user-images.githubusercontent.com/33479935/97126552-1fabde80-1772-11eb-9729-42bb4087fbdd.png)

根据我目前项目亲测，并不一定一定需要是 history 模式 ，只要浏览器支持 history.pushState 就可以。

**Comment by mcuking** [comment]
你好，感谢指出问题，已经修改好了～
